firstname=input("enter the first name")
lastname=input("enter the second name")
a=firstname+lastname
print(a[::-1])
b=int(input("enter first number"))
c=int(input("enter second number"))
print("addition",b+c)
print("subtraction",b-c)
print("multiplication",b*c)
print("division",b/c)
print("remainder",b%c)